# Generated by Django 4.1.6 on 2023-02-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_post_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='blockquote',
        ),
        migrations.RemoveField(
            model_name='items',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='items',
            name='catname',
        ),
        migrations.RemoveField(
            model_name='items',
            name='description',
        ),
        migrations.RemoveField(
            model_name='items',
            name='thumb',
        ),
    ]
